/**
 * runId-aware DB writers used from inside the intake workflow's tools.
 *
 * Every helper here is small and tolerant — a failed write must NEVER abort
 * a tool execution. The agent's job is to produce the artifact; persistence
 * is best-effort observability.
 */

import { createHash } from "node:crypto"
import {
  cleanedPayloads,
  eq,
  getDb,
  intakeMessages,
  intakeRuns,
  intakeSteps,
  scrapeProvenance,
  type CleanedPayload as CleanedPayloadRow,
  type IntakeStep,
  type ScrapeProvenance,
} from "@buildinaus/database"
import type { CleanedPayload, Finalize, Plan } from "./schemas"

export interface IntakeRunContext {
  /** intake_runs.id (uuid) — generated by the route handler before the workflow starts. */
  runId: string
  /** Linked user, or null for anonymous runs. */
  userId: number | null
}

/* ── Step ── */

interface StepInput {
  stepName: string
  attempt?: number
  status?: "succeeded" | "failed" | "skipped"
  modelId?: string
  gatewayRequestId?: string
  inputTokens?: number
  outputTokens?: number
  costUsd?: number
  errorText?: string
  startedAt?: Date
  finishedAt?: Date
}

export async function recordStep(
  runId: string,
  step: StepInput,
): Promise<IntakeStep | null> {
  try {
    const db = getDb()
    const [row] = await db
      .insert(intakeSteps)
      .values({
        runId,
        stepName: step.stepName,
        attempt: step.attempt ?? 1,
        status: step.status ?? "succeeded",
        modelId: step.modelId,
        gatewayRequestId: step.gatewayRequestId,
        inputTokens: step.inputTokens,
        outputTokens: step.outputTokens,
        costUsd: step.costUsd?.toString(),
        errorText: step.errorText,
        startedAt: step.startedAt ?? new Date(),
        finishedAt: step.finishedAt ?? new Date(),
      })
      .returning()
    return row ?? null
  } catch (err) {
    console.warn("[persistence] recordStep failed", { runId, err })
    return null
  }
}

/* ── Scrape ── */

export interface RecordScrapeInput {
  url: string
  provider: "firecrawl" | "fetch"
  status?: number
  /** Normalised markdown text — used to compute the content hash. */
  markdown: string
  cacheHit: boolean
  /** Set when the scout uploaded the raw HTML to Vercel Blob. */
  htmlBlobUrl?: string
  htmlBlobPathname?: string
}

export async function recordScrape(
  runId: string,
  input: RecordScrapeInput,
): Promise<ScrapeProvenance | null> {
  "use step"
  try {
    const db = getDb()
    const contentHash = createHash("sha256")
      .update(input.markdown)
      .digest("hex")
    const [row] = await db
      .insert(scrapeProvenance)
      .values({
        runId,
        url: input.url,
        provider: input.provider,
        status: input.status,
        contentHash,
        cacheHit: input.cacheHit,
        htmlBlobUrl: input.htmlBlobUrl,
        htmlBlobPathname: input.htmlBlobPathname,
      })
      .returning()
    return row ?? null
  } catch (err) {
    console.warn("[persistence] recordScrape failed", { runId, err })
    return null
  }
}

/* ── Cleaned payload ── */

export async function recordCleanedPayload(
  runId: string,
  payload: CleanedPayload,
  meta: { sourceUrl?: string; confidence?: number } = {},
): Promise<CleanedPayloadRow | null> {
  try {
    const db = getDb()
    const kind = payload.type === "startup" ? "company" : payload.type
    const [row] = await db
      .insert(cleanedPayloads)
      .values({
        runId,
        kind,
        payload: payload.data as Record<string, unknown>,
        sourceUrl: meta.sourceUrl,
        confidence: meta.confidence,
        status: "drafted",
      })
      .returning()
    return row ?? null
  } catch (err) {
    console.warn("[persistence] recordCleanedPayload failed", { runId, err })
    return null
  }
}

/* ── Run lifecycle ── */

export async function recordPlan(
  runId: string,
  plan: Plan,
): Promise<void> {
  try {
    const db = getDb()
    await db
      .update(intakeRuns)
      .set({ intent: plan.intent })
      .where(eq(intakeRuns.id, runId))
  } catch (err) {
    console.warn("[persistence] recordPlan failed", { runId, err })
  }
}

export async function finalizeRun(
  runId: string,
  finalize: Finalize,
): Promise<void> {
  try {
    const db = getDb()
    await db
      .update(intakeRuns)
      .set({
        status: finalize.outcome === "error" ? "failed" : "completed",
        outcome: finalize.outcome,
        redirectUrl: finalize.redirect_url,
        summaryMarkdown: finalize.summary_markdown,
        finishedAt: new Date(),
      })
      .where(eq(intakeRuns.id, runId))
  } catch (err) {
    console.warn("[persistence] finalizeRun failed", { runId, err })
  }
}

export async function failRun(runId: string, errorText: string): Promise<void> {
  try {
    const db = getDb()
    await db
      .update(intakeRuns)
      .set({
        status: "failed",
        outcome: "error",
        summaryMarkdown: errorText.slice(0, 4_000),
        finishedAt: new Date(),
      })
      .where(eq(intakeRuns.id, runId))
  } catch (err) {
    console.warn("[persistence] failRun failed", { runId, err })
  }
}

/* ── Messages ── */

interface MessageRecord {
  role: "user" | "assistant" | "system"
  parts: unknown
}

export async function appendMessages(
  runId: string,
  messages: MessageRecord[],
): Promise<void> {
  if (messages.length === 0) return
  try {
    const db = getDb()
    await db.insert(intakeMessages).values(
      messages.map((m) => ({
        runId,
        role: m.role,
        parts: m.parts as Record<string, unknown>,
      })),
    )
  } catch (err) {
    console.warn("[persistence] appendMessages failed", { runId, err })
  }
}
