import { Suspense } from "react"
import Link from "next/link"
import { notFound } from "next/navigation"
import {
  ArrowLeft,
  ArrowUpRight,
  Briefcase,
  CalendarDays,
  MapPin,
  Sparkles,
  Star,
  Users,
  Zap,
} from "lucide-react"
import { PageShell, Panel, PanelHeader } from "@/components/layout/page-shell"
import {
  DetailHeaderSkeleton,
  DetailBodySkeleton,
} from "@/components/layout/skeletons"
import type { Company, Event, Founder, Job } from "@buildinaus/types"
import { listFounders } from "@/lib/data/founders"
import {
  getTailoredPage,
  typeLabel,
  type TailoredBlock,
} from "@/lib/tailored"

export async function generateStaticParams() {
  const founders = await listFounders()
  return founders.map((f) => ({ slug: f.slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  return {
    title: `Tailored one-pager · ${slug} · BuildinAus`,
    description:
      "An agent-curated, personalised view of the Australian startup ecosystem.",
  }
}

export default function TailoredPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  return (
    <PageShell>
      <BackLink params={params} />
      <Suspense
        fallback={
          <>
            <DetailHeaderSkeleton />
            <DetailBodySkeleton />
          </>
        }
      >
        <TailoredContent params={params} />
      </Suspense>
    </PageShell>
  )
}

async function BackLink({ params }: { params: Promise<{ slug: string }> }) {
  // Static text — only the href needs the slug. Awaiting params here is
  // cheap and keeps the back button visible while the body suspends.
  const { slug } = await params
  return (
    <Link
      href={`/founders/${slug}`}
      className="inline-flex items-center gap-1.5 text-xs text-muted-foreground transition-colors hover:text-foreground"
    >
      <ArrowLeft className="h-3 w-3" />
      Back to profile
    </Link>
  )
}

async function TailoredContent({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const page = await getTailoredPage(slug)
  if (!page) notFound()

  const headline = page.blocks.find((b) => b.kind === "headline")
  const rest = page.blocks.filter((b) => b.kind !== "headline")

  return (
    <>
      <header className="mt-6 flex flex-col items-start justify-between gap-6 border-b border-border/60 pb-10 md:flex-row md:items-end">
        <div className="max-w-2xl">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-border/80 bg-card/50 px-2.5 py-1 font-mono text-[11px] uppercase tracking-[0.14em] text-muted-foreground">
            <Sparkles className="h-3 w-3" />
            Tailored one-pager
          </div>
          {headline && (
            <>
              <h1 className="text-balance text-3xl font-medium tracking-tight md:text-5xl">
                {headline.title}
              </h1>
              {headline.body && (
                <p className="mt-3 text-pretty text-base leading-relaxed text-muted-foreground">
                  {headline.body}
                </p>
              )}
            </>
          )}
        </div>

        <CacheBadge
          fingerprint={page.fingerprint}
          cacheHit={page.cacheHit}
          generationMs={page.generationMs}
          modelHint={page.modelHint}
        />
      </header>

      <div className="mt-10 grid auto-rows-[minmax(0,1fr)] gap-3 lg:grid-cols-6">
        {rest.map((block) => (
          <BlockRenderer key={block.id} block={block} />
        ))}
      </div>

      <p className="mt-10 text-center font-mono text-[11px] uppercase tracking-[0.14em] text-muted-foreground/70">
        Generated by an agent · refreshes every 6 hours · cohort key{" "}
        <span className="text-foreground/70">{page.fingerprint}</span>
      </p>
    </>
  )
}

function CacheBadge({
  fingerprint,
  cacheHit,
  generationMs,
  modelHint,
}: {
  fingerprint: string
  cacheHit: boolean
  generationMs: number
  modelHint: string
}) {
  return (
    <div className="rounded-xl border border-border/80 bg-card/60 p-4 font-mono text-[11px] leading-relaxed text-muted-foreground">
      <div className="flex items-center gap-1.5 text-foreground">
        <Zap className="h-3 w-3" />
        <span className="uppercase tracking-wider">
          {cacheHit ? "Cache hit" : "Generated"}
        </span>
      </div>
      <div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1">
        <span>Cohort</span>
        <span className="text-right text-foreground/80">{fingerprint}</span>
        <span>Gen latency</span>
        <span className="text-right text-foreground/80">{generationMs}ms</span>
        <span>Model</span>
        <span className="text-right text-foreground/80">{modelHint}</span>
      </div>
    </div>
  )
}

function BlockRenderer({ block }: { block: TailoredBlock }) {
  switch (block.kind) {
    case "company-spotlight":
      return <SpotlightBlock block={block} />
    case "jobs":
      return <JobsBlock block={block} />
    case "events":
      return <EventsBlock block={block} />
    case "founders":
      return <FoundersBlock block={block} />
    case "narrative":
      return <NarrativeBlock block={block} />
    default:
      return null
  }
}

function SpotlightBlock({ block }: { block: TailoredBlock }) {
  const company = block.data as Company
  return (
    <Panel className="lg:col-span-4 lg:row-span-2">
      <PanelHeader icon={<Star className="h-3.5 w-3.5" />} label={block.title} />
      <div className="flex flex-1 flex-col justify-between gap-6 p-6">
        <div>
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg border border-border/80 bg-gradient-to-b from-muted/60 to-muted/20 font-mono text-lg font-medium">
              {company.name[0]}
            </div>
            <div>
              <div className="text-lg font-medium tracking-tight">{company.name}</div>
              <div className="text-xs text-muted-foreground">
                {company.city} · {company.stage}
              </div>
            </div>
          </div>
          <p className="mt-4 max-w-md text-pretty text-base leading-relaxed text-foreground/90">
            {block.body}
          </p>
        </div>
        <div className="flex items-end justify-between border-t border-border/60 pt-5">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
              {company.metric.label}
            </div>
            <div className="mt-1 text-3xl font-medium tabular-nums">{company.metric.value}</div>
          </div>
          <Link
            href={`/companies/${company.slug}`}
            className="inline-flex items-center gap-1.5 rounded-md border border-border/80 bg-muted/40 px-3 py-1.5 text-xs font-medium transition-colors hover:border-foreground/30"
          >
            View profile
            <ArrowUpRight className="h-3.5 w-3.5" />
          </Link>
        </div>
      </div>
    </Panel>
  )
}

function JobsBlock({ block }: { block: TailoredBlock }) {
  const jobs = block.data as Job[]
  return (
    <Panel className="lg:col-span-2">
      <PanelHeader icon={<Briefcase className="h-3.5 w-3.5" />} label={block.title} />
      {block.body && (
        <p className="px-6 pt-4 text-xs leading-relaxed text-muted-foreground">{block.body}</p>
      )}
      <ul className="mt-2 flex-1 divide-y divide-border/60">
        {jobs.map((job) => (
          <li key={job.id} className="group">
            <Link
              href={`/jobs/${job.id}`}
              className="flex items-center justify-between gap-3 px-6 py-3 transition-colors hover:bg-muted/30"
            >
              <div className="min-w-0">
                <div className="truncate text-sm font-medium">{job.title}</div>
                <div className="truncate text-xs text-muted-foreground">
                  {job.city} · {job.salary}
                </div>
              </div>
              <ArrowUpRight className="h-4 w-4 shrink-0 text-muted-foreground transition-all group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-foreground" />
            </Link>
          </li>
        ))}
      </ul>
    </Panel>
  )
}

function FoundersBlock({ block }: { block: TailoredBlock }) {
  const peers = block.data as Founder[]
  return (
    <Panel className="lg:col-span-3">
      <PanelHeader icon={<Users className="h-3.5 w-3.5" />} label={block.title} />
      {block.body && (
        <p className="px-6 pt-4 text-xs leading-relaxed text-muted-foreground">{block.body}</p>
      )}
      <ul className="mt-2 flex-1 divide-y divide-border/60">
        {peers.map((p) => (
          <li key={p.slug} className="group">
            <Link
              href={`/founders/${p.slug}`}
              className="flex items-center justify-between gap-3 px-6 py-3 transition-colors hover:bg-muted/30"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full border border-border bg-muted/60 font-mono text-[11px]">
                  {p.name
                    .split(" ")
                    .map((n) => n[0])
                    .join("")}
                </div>
                <div>
                  <div className="text-sm font-medium">{p.name}</div>
                  <div className="text-xs text-muted-foreground">
                    {p.role} · {typeLabel(p.type)}
                  </div>
                </div>
              </div>
              <ArrowUpRight className="h-4 w-4 text-muted-foreground transition-all group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-foreground" />
            </Link>
          </li>
        ))}
      </ul>
    </Panel>
  )
}

function EventsBlock({ block }: { block: TailoredBlock }) {
  const events = block.data as Event[]
  return (
    <Panel className="lg:col-span-3">
      <PanelHeader icon={<CalendarDays className="h-3.5 w-3.5" />} label={block.title} />
      <ul className="flex-1 divide-y divide-border/60">
        {events.map((ev) => (
          <li key={ev.id} className="group">
            <Link
              href={`/events/${ev.id}`}
              className="flex items-center justify-between gap-3 px-6 py-3 transition-colors hover:bg-muted/30"
            >
              <div className="min-w-0">
                <div className="truncate text-sm font-medium">{ev.title}</div>
                <div className="truncate text-xs text-muted-foreground">
                  <MapPin className="mr-1 inline h-3 w-3" />
                  {ev.city} · {ev.startsAt}
                </div>
              </div>
              <span className="rounded-md border border-border/80 bg-muted/40 px-2 py-0.5 font-mono text-[11px] tabular-nums text-muted-foreground">
                {ev.rsvp}
              </span>
            </Link>
          </li>
        ))}
      </ul>
    </Panel>
  )
}

function NarrativeBlock({ block }: { block: TailoredBlock }) {
  return (
    <Panel className="lg:col-span-6">
      <PanelHeader icon={<Sparkles className="h-3.5 w-3.5" />} label={block.title} />
      <p className="p-6 text-pretty text-[15px] leading-relaxed text-foreground/80">
        {block.body}
      </p>
    </Panel>
  )
}
